services:
    postgres:
        image: postgres:16.1
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: <password>
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: <email>
            PGADMIN_DEFAULT_PASSWORD: <password>
